### ISSUE TITLE
Terminal broken

### ISSUE THREAD

**Issue by dannycreations** [Sylkadi/BrutalCompanyMinus#11]
when disabling all "Remove Enemy" it broke terminal and cannot leave unless alt+f4

DrinkableWater-Brutal_Company_Minus-0.8.0
[BrutalCompanyMinus.txt](https://github.com/Sylkadi/BrutalCompanyMinus/files/14231667/BrutalCompanyMinus.txt)

**Comment by Sylkadi** [comment]
Easier way of doing it is just setting the removeEnemy eventType weight to 0, but thanks for letting me now

**Comment by Sylkadi** [comment]
Should be fixed in latest
