### ISSUE TITLE
Custom monsters

### ISSUE THREAD

**Issue by Qugar** [Sylkadi/BrutalCompanyMinus#12]
Would it be possible to add events for custom monsters?

Maybe 5-10 empty events where you enter the name of the monster and everything else and the mod then takes the name in order to be able to spawn them? Of course these would be off by default.

**Comment by Sylkadi** [comment]
I already have it set up to do that, so easily. Probably next release, probably.

**Comment by Qugar** [comment]
Works wonderfully, thank you.

Great mod and great modder.

Tested with:
Don't Touch Me - DTMEnemy
Shockwave Drone - DroneEnemy
Shrimp - ShrimpEnemy
Shy Guy - ShyGuyDef
Peeper - PeeperType

**Comment by Qugar** [comment]
Would there be a way to make the number of custom monster events unlimited? Maybe by the mod recognizing that a new custom monster event has been added and then adding another entry in the config after starting the game or something? I actually already have 10.

If not, could you perhaps increase the number to 20 in the next update?

Thanks in advance whatever you decide, even if you say you don't want to add more than 10.

**Comment by Sylkadi** [comment]
Done in next release
