### ISSUE TITLE
Disappearing Scrap (Slayer Shotgun, Turret, etc.)

### ISSUE THREAD

**Issue by IronPokemaster** [Sylkadi/BrutalCompanyMinus#14]
As stated in the title, I have recently encountered a bug to do with the mod’s scrap, specifically Turrets, Landmines, Slayer Shotgun and Slayer Shells. Whenever the save is reloaded, these items disappear from the ship.

I’ve done testing and it appears that the reason may be because they don’t seem to have a corresponding ID when I check with mods such as DanceTools, rendering the game to be unable to save them, though I’m not 100% sure.

**Comment by Sylkadi** [comment]
Fixed in next release, whenever that is
