### ISSUE TITLE
Config Editor Spam

### ISSUE THREAD

**Issue by Qugar** [Sylkadi/BrutalCompanyMinus#16]
Would it be possible not to generate the configs for the moon weights if you marked these options as false?

As it is now, it creates spam in the config editor, there are people who have 15-20 moons installed plus the 9 vanilla moons, which then creates tons of entries in the config editor, even if you don't use this option at all.

**Comment by Sylkadi** [comment]
Added _Enable option to disable.

**Comment by Qugar** [comment]
Thank you. :smile:
