### ISSUE TITLE
[Request] Add a "Nothing" EventType weight value

### ISSUE THREAD

**Issue by AfterRebelion** [Sylkadi/BrutalCompanyMinus#19]
### Prologue
Really loving the mod, specially the Weather Multipliers and Events, and how configurable all is.
However, I want to "tone it down" for my group session, to be more casual.
One way I was thinking of doing that, is to make events more far in between, so they are something uncommon to find when we land on a moon, instead of all landings having some type of event always going on.
The only way I currently found to do this, is increase the weight of the "Neutral" EventType considerably, that has a "Nothing" type of event that can occur. However when playtesting, this resulted in the most common type of landing being infested by trees.
Having trees in moons they are not supposed to is nice as a rare occurrence, however quickly becomes weird if it's in almost every landing.
#### Config
This is the current values on the config I'm testing:
Number of events: 2

_EventType Weights:
|||
|-|-|
| VeryGood | 4 |
| Good | 25 |
| Neutral | 50 |
| Bad | 5 |
| VeryBad | 1 | 
| Remove | 15 | 

### Request
Add a "Nothing" EventType, defaulted to 0, to let people like myself control how common it is for no event to be selected from the pool.

### Workaround
I could enable the "Use custom weights?" setting, and increase the weight of the "Nothing" Event inside the "Neutral" EventType, however this has several disadvantages:
- If there are any new events added in a mod update, I need to retweak the values again every time.
- It's harder to adjust the proper value in line with all other EventTypes, to get my desired results.
  - My config (and the default one) has all EventType weight values to sum 100, so it acts as a percentile weight, making it easier to adjust to my preferences.

**Comment by Sylkadi** [comment]
Another thing that you can do is disable Trees, Leafless trees, Leafless brown trees, Rain, Heavy rain and gloomy, which is every other neutral event other than nothing.

I'll work something out.

**Comment by Sylkadi** [comment]
This will be the solution, though need to do other things before i release.

This isn't what you requested, but can be used to do the same thing.

![Screenshot_149](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/6878cabb-5ed3-4a40-b250-5b75de5b3eb6)

**Comment by AfterRebelion** [comment]
Hi!
Been testing the new configs, and they work great for what I want to accomplish. They are even more useful than what could be done with my original suggestion.
