### ISSUE TITLE
[Request] Nutslayer Invinciblity

### ISSUE THREAD

**Issue by bobfreyfrediam** [Sylkadi/BrutalCompanyMinus#20]
As title says, maybe a config to give him more health or make him unkillable, as the gun drop immediately negates the rest of the game

**Comment by Sylkadi** [comment]
Sure thing, but I'm also going to change the AI a little to be much more harsh...

**Comment by Sylkadi** [comment]
Added immortality config setting, but I also made the nutcracker drastically stronger.

**Comment by bobfreyfrediam** [comment]
great!
