### ISSUE TITLE
Overcomplicated config

### ISSUE THREAD

**Issue by Qugar** [Sylkadi/BrutalCompanyMinus#22]
First of all, I don't want to come across as mean and I'm sure you'll do your best for this mod.

However, I am confused and find the new config overcomplicated. I now have to set the whole config again and I no longer understand what I should enter there.

The problem may be entirely mine but I have to ask a few questions.

1. Is it a mistake that commas are used in one config and dots in the other?

![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/9737a60b-24f2-44a0-bded-80fa56dc74a9)
![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/7199366e-37a2-456e-8c97-2ea91c340a6d)

2. What do MinCap and MaxCap mean and do they also apply outside of the event? If they only apply to the events, isn't BaseScale equal to MinCap?

3. I know that some things were there before, like InsideEnemyRarity, now I'm wondering if I always misunderstood that, does this apply outside of the events?

Sorry for the stupid questions, but I'm confused now.

**Comment by Sylkadi** [comment]
I was trying to compact the config.

25, 0.84, 25, 75 is Equivalent to
- **Base:** 25
- **Increment**: 0.84
- **MinCap**: 25
- **MaxCap**: 75 

MinCap and MaxCap are just the range of values possible so it wont go any higher than 75 when computed or lower than 25, and yes base is equal to min.

In the Difficulty_Settings config there's a setting to ignore the cap so it would scale infinitely.

1 - No
3 - I don't know what you misunderstood.

**Comment by Qugar** [comment]
1. That means I have to write the decimal numbers with commas in one config and with dots in the other? Or is it simply interchangeable?

Don't get me wrong, I don't know how it works in C# but from my layman's experience it would read like this:

- BaseScale: 25
- IncrementScale: 0
- MinCap: 84
- MaxCap: 25
- The last 75 would be ignored because it is not queried.

At least in other programming languages ​​a dot or a comma makes a difference, that's why I ask. But as I said, I have no idea how it works in C#.

3. Well, do InsideEnemyRarity and OutsideEnemyRarity have an impact outside of the events? If so, does it overwrite the AdvancedCompany values ​​that I can set individually per level?

Thanks for your answers and sorry for the inconvenience.

**Comment by Sylkadi** [comment]
The comma is a separator and not interchangeable. So each number is separated by a comma not a dot.

InsideEnemyRarity and OutsideEnemyRarity wont conflict with advanced company since it doesn't change the rarity but adds the enemy with rarity to the spawnable enemy list, which can result in there being 2 hoarding bugs in the list (Intended).

**Comment by Qugar** [comment]
But you use a comma for the decimal number instead of a dot. That's why it would recognize it as a separator, that's what confuses me so much.

![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/3e627215-5379-46e6-b2c3-f9caaba81d36)

**Comment by Sylkadi** [comment]
what the fuck

**Comment by Qugar** [comment]
Sorry if I'm tiring, I'm probably just stupid at the moment.

**Comment by Sylkadi** [comment]
No your not

**Comment by Sylkadi** [comment]
what event were you looking at? cause all configs look normal to me

**Comment by Qugar** [comment]
AntiCoilhead but this is shown everywhere in my event config.

**Comment by Qugar** [comment]
I'll just delete the config and recreate it, maybe that's an error that happened during the update.

**Comment by Sylkadi** [comment]
I just regenerated config and looks normal to me...

![Screenshot_158](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/4df5fad8-912d-423e-b540-316bb86779b5)

**Comment by Qugar** [comment]
![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/c0baaf33-5b1d-40c2-a659-53c18729cd7f)

This is what it looks like for me after deleting it. Is it possible that it is doing this because I am from Germany? Here we use commas instead of dots for decimal numbers.

**Comment by Sylkadi** [comment]
Can you copy paste the the scales here? Id it is the dot character but it looks exactly the same as the comma

**Comment by Qugar** [comment]
25, 0,84, 25, 75

Like this?

Otherwise I can just send you the config.

[Events.zip](https://github.com/Sylkadi/BrutalCompanyMinus/files/14387156/Events.zip)

**Comment by Sylkadi** [comment]
One final thing. Start the game and launch and have ui enabled. And show me these numbers.
![Screenshot_159](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/bd2e0cd5-ba14-4dbe-a25b-8a2061dd5003)

**Comment by Qugar** [comment]
![grafik](https://github.com/Sylkadi/BrutalCompanyMinus/assets/8191849/2c1fb841-71a4-4a93-a080-69c5d2d69112)

**Comment by Sylkadi** [comment]
Lol, If you live in germany you get the hardcore config... hahahahahha

**Comment by Qugar** [comment]
Wow seriously? :joy:

Can you get this solved somehow please? :sweat:

**Comment by Sylkadi** [comment]
Im looking into it

**Comment by Qugar** [comment]
I don't know if it helps you but this only happens in Events.cfg

But it doesn't happen in the Difficulty_Settings.cfg

**Comment by Sylkadi** [comment]
Can you send the entire config, should all be in one folder
![Screenshot_160](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/95653ed2-5c1a-4bb9-89cb-8dc37b769df8)
Just need to confirm something then i publish

**Comment by Qugar** [comment]
[BrutalCompanyMinus.zip](https://github.com/Sylkadi/BrutalCompanyMinus/files/14388748/BrutalCompanyMinus.zip)

**Comment by Sylkadi** [comment]
Should be up, don't know when it will appear on thunderstore

**Comment by Qugar** [comment]
I'll take a look at it as soon as I can and give you feeback.

Thank you for your effort.

**Comment by Qugar** [comment]
Looks like it's working now.

Thanks again for your great work and sorry that I didn't find the right words to better explain my problem from the beginning. :thumbsup:

**Comment by Qugar** [comment]
One last question for which I don't want to open an issue.

Would it be possible to add a time option for the UI in the config with the next update? I only display the events and the UI is there for far too long.
