### ISSUE TITLE
Two errors caused me to have a black screen when creating a room

### ISSUE THREAD

**Issue by apeng0907** [Sylkadi/BrutalCompanyMinus#24]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LethalProgression.Skills.Oxygen.OxygenUpdate (GameNetcodeStuff.PlayerControllerB __instance) (at <921abc4e643b402eb381ff4e93321c57>:IL_0001)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MoreShipUpgrades.UpgradeComponents.Items.Wheelbarrow.WheelbarrowScript.CheckIfPlayerCarryingWheelbarrowLookSensitivity (System.Single defaultValue) (at <6c89dd0819464aec859e1964fb85ca32>:IL_0044)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::PlayerLookInput>(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

**Comment by Sylkadi** [comment]
You sure this is caused by my mod? These errors are from LateGameUpgrades and LethalProgression.

**Comment by apeng0907** [comment]
The old version will not appear, perhaps due to mod conflicts. When I installed BrutalCompany, these two errors appeared and the screen went black when creating a room. At that time, deleting this mod would make it normal.

**Comment by Sylkadi** [comment]
Can you give full log file

**Comment by apeng0907** [comment]
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14428834/LogOutput.log)

**Comment by Sylkadi** [comment]
Fixed for next release, though i don't know which mod is the culprit
