### ISSUE TITLE
Terminal options have been removed?

### ISSUE THREAD

**Issue by TinyDerp** [Sylkadi/BrutalCompanyMinus#25]
Have the terminal options been removed? I want to turn of the weights shoving in the moon list but there isn't an option to do that. It makes the mod unreadable when used together with [ShowMoonPriceLLL](https://thunderstore.io/c/lethal-company/p/AboveFire/ShowMoonPriceLLL/). 
Could you add back the option to disable this feature or make the mod more readable when used together with other mods?

**Comment by Sylkadi** [comment]
Option hasn't been removed, it's in \BrutalCompanyMinus\Weather_Settings

**Comment by TinyDerp** [comment]
damm im dumb
