### ISSUE TITLE
Disabling Difficulty Day

### ISSUE THREAD

**Issue by shikigami-chen** [Sylkadi/BrutalCompanyMinus#26]
Me and my friends play with BCM on basically all the time, but we weren't really a fan of the "spawn chance, max inside power, bonus enemy hp" etc stuff that was added with 9.0.  I've been able to disable those in the config, but I don't know how to disable the "Difficulty Day 22" type thing it does.  Is it possible to disable or at least can I get an explanation on how that modifies the game?

**Comment by Sylkadi** [comment]
The 'day' number has always been there though with 0.9.0 it's now in the UI. This is number is used to scale everything, this also scales most events as well. You can't disable that.
