### ISSUE TITLE
[Warning]something isn't matched with enum, this may cause issues...

### ISSUE THREAD

**Issue by apeng0907** [Sylkadi/BrutalCompanyMinus#27]
[Info   :BrutalCompanyMinus] Generating 'EnemyList'
[Warning:BrutalCompanyMinus] Enemy:Puffer_0, prefab is null, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:HaltEnemy, prefab is null, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'Knight', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'Puffer_0', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'ShyGuyDef', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'SkibidiDef', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'HaltEnemy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'ShrimpEnemy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'Herobrine', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'DTMEnemy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'ImmortalSnail.EnemyType', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'DroneEnemy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'KamikazieBug', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'AntiCoilHead', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'NutSlayer', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'LockerEnemy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Enemy:'WalkerType', isn't matched with enum, this may cause issues...
[Info   :BrutalCompanyMinus] Finished generating 'EnemyList', Count:35
[Info   :BrutalCompanyMinus] Generating 'ItemList'
[Warning:BrutalCompanyMinus] Item:CardboardBox, prefab is null, this may cause issues...
[Warning:BrutalCompanyMinus] Item:StickyNote, prefab is null, this may cause issues...
[Warning:BrutalCompanyMinus] Item:Clipboard, prefab is null, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PolaroidItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'TpButton', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'NightVisionItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'MedKitMapItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'HelmetItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'StoreWheelbarrowItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'coilHead', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'TpButtonAdv', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'DivingKitItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GeigerCounterItemDef', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ScrapCannon', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Boombox', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ExtensionLadder', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Flashlight', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Jetpack', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'LockPicker', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ProFlashlight', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'RadarBooster', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Shovel', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SprayPaint', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'StunGrenade', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'TZPInhalant', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WalkieTalkie', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ZapGun', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GunAmmo', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ScarletPro-flashlight', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ScarletFlashlight', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'CardboardBox', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'StickyNote', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Shotgun', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'RedLocustHive', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Ragdoll', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'MapDevice', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'LungApparatus', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Key', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Clipboard', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Binoculars', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Golden Shovel Special', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SmokeSmokeFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SmileFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'OpOpFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GumGumFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'FlameFlameFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ChopChopFruit', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WetFloorSign', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PoolBall', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'LifeBuoy', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PoolNet', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SpiderEggItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WhiteOrbItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BlackOrbItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GuiltyGearCaseItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'OrangeOrbItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'MooMooItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'FireAxe', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WeezerGuitar', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'CrownItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Tragedyplushitem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'jesterplushie', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'lootbugPlush', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'comedyplushitem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'CoilHeadPlush', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BunkspidItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BrackenPlush', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ChipBag', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'RockingHorse', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'EnergyCore', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'TypeWriter', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ArmyHelmet', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ArmyCanteen', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WireSpool', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'OldRadio', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'WheelRim', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Gramophone', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'RubberChickenItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PictureItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'LandmineItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'RedstoneTorch', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'FlandreCrystalItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PaintingItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GrabbableTurret', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GrabbableLandmine', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SlayerShotgun', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'PentagramItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BaboonHawkSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ScavItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'HoardingBugSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'EyelessDogSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BombItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'DiscItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Bones', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ThumperSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'DataPCItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ExorcLootItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Crucifix', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Teddy Bear', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BunkerSpiderSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SnareFleaSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'HoardingEggItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'MedKitItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'EggLootItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BrackenSample', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Heart', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'candelabraItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'ScrapWheelbarrowItem', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'MP3', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'GreatChest', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Ruby', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'SilverBar', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Chest', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'BronzeBar', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Emerald', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Diamond', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Item:'Pickaxe', isn't matched with enum, this may cause issues...
[Info   :BrutalCompanyMinus] Finished generating 'ItemList', Count:161
[Info   :BrutalCompanyMinus] Generating 'ObjectList'
[Warning:BrutalCompanyMinus] Object:'MedKitMap', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'ScrapWheelbarrow', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'ScavExtract', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'HoardingBugEggs', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'DataPC', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Heart', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Crucifix', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'candelabra', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Teddy Bear', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Bones', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Pentagram', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'Bomb', isn't matched with enum, this may cause issues...
[Warning:BrutalCompanyMinus] Object:'MissileTurret', isn't matched with enum, this may cause issues...
[Info   :BrutalCompanyMinus] Finished generating 'ObjectList', Count:26
[Info   :BrutalCompanyMinus] Map Count:0

**Comment by Sylkadi** [comment]
Looks normal to me, can be ignored. If the game is breaking, please give the full log file and reopen this issue.

These are warnings not errors.
