### ISSUE TITLE
Can you tell me the formula for calculating Quota？

### ISSUE THREAD

**Issue by apeng0907** [Sylkadi/BrutalCompanyMinus#28]
What is the relationship between the final quota and these three factors？

Starting Quota、Base Increase、Increase Steepness

**Comment by Sylkadi** [comment]
The source code for the formula is

![Screenshot_182](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/b76ba011-e4bd-475e-b283-29f1717a8a74)

And this is what the wiki says

![Screenshot_183](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/5e77b450-a984-45eb-ac71-c2fe47de7996)

Which can be found here https://lethal.miraheze.org/wiki/Quota

These are used to calculate the next quota.
