### ISSUE TITLE
v0.10.3 DDay event bugs

### ISSUE THREAD

**Issue by ByakkoSamma** [Sylkadi/BrutalCompanyMinus#29]
- DDay event siren is too louder.
 - DDay was triggered in Vow and March only, after it, event and siren's sound kept triggering in other moons and even with the ship in orbit.
 - Host and users' mod console thrown errors indicating that DDay event's explosion sound couldn't be played and loops in that error, making fps drops.

Maybe these clips can help:
  https://youtu.be/cf6z6m894mU
  https://youtu.be/pfQKOw0j7o0

**Comment by Sylkadi** [comment]
![Screenshot_178](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/a27772aa-3647-4632-bfc3-f44795435da3)
![Screenshot_179](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/6f442882-2969-45c1-81c3-207a44be9de2)

If possible can you give the full log file

**Comment by Sylkadi** [comment]
Should be fixed in next release, if this still persists reopen this issue.
