### ISSUE TITLE
The idea is to add a config, the point of which is to increase the probability of bad events if you rack up more scrap than your quota.

### ISSUE THREAD

**Issue by M0rsus** [Sylkadi/BrutalCompanyMinus#33]
Hi, I wish there was a settings where bad events would happen more often not only because of days gone by, but also for exceeding the quota, to make mining on "farming" moons more difficult and make life harder for experienced players who can easily take out a lot of scrap.

You could add settings such as:
-how much the quota needs to be exceeded for the chance of bad events to start increasing and the chance of good events to start decreasing
-How quickly the chance of bad events will increase and the chance of good events will decrease.
-The closer the last day is to the quota, the higher the chance of bad events

It would be very cool if such customisations were added^_^

**Comment by Sylkadi** [comment]
I would like to add something to discourage players from playing one map all the time and encourage other maps to be played by maybe guaranteeing bad/very bad events or good/very good events, but i'm unsure of exactly what I want to do, I know BCP has a heat system.

Currently very bad events will become more often as days pass and bad ones less and they will go from
**Bad**   (day:0 => 43 to day:60 => 23)
**VeryBad** (day:0 => 10 to day:60 => 30)

As for your request I could add config options to also scale by how many days passed, how much scrap is in the ship, time passed, days till deadline and more.

But i'm unsure yet, I'd have to think about it.

**Comment by M0rsus** [comment]
Ok, glad you answered, scaling by the amount of scrap on the ship will be enough for me^_^, I will wait for further mod updates, good luck in development

**Comment by Sylkadi** [comment]
There is now an option for that in the config in latest.

**Comment by M0rsus** [comment]
thank you very much^_^
