### ISSUE TITLE
The mod is skipped due to an error

### ISSUE THREAD

**Issue by EithanLlanos** [Sylkadi/BrutalCompanyMinus#34]
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14973503/LogOutput.log)

I was trying to play since some hours ago and I cant make the mod work, I tried with previous versions like 0.10.12 and works well.
The mod was executed alone

**Comment by Sylkadi** [comment]
The log file you gave me has no errors(0.10.12 log file), I tried the latest version of brutal company minus alone and it works fine.

**Comment by EithanLlanos** [comment]
> The log file you gave me has no errors(0.10.12 log file), I tried the latest version of brutal company minus alone and it works fine.


My bad haha, here is the log file, sorry.
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14975617/LogOutput.log)

**Comment by Sylkadi** [comment]
Are you still running beta or on v49?, cause latest versions(0.11.0) and above will only work with v50

**Comment by EithanLlanos** [comment]
> Are you still running beta or on v49?, cause latest versions(0.11.0) and above will only work with v50

I didn really play the v50 yet, I wanna do it with the modpack working, but I think Im on the version
![image](https://github.com/Sylkadi/BrutalCompanyMinus/assets/131002657/c353c392-4d0c-45b8-b17c-511a30bd7051)
![image](https://github.com/Sylkadi/BrutalCompanyMinus/assets/131002657/fdf79215-43ad-4be0-aaba-e94461a22637)

**Comment by Sylkadi** [comment]
LehalCompany -> Properties -> Betas -> Beta participation -> None
![Screenshot_239](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/f74602b0-7f54-489b-b87f-f19e76d9789e)
![Screenshot_238](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/a205d222-abaf-44fb-bcf3-ca566ade1209)

My only explanation is that you are running on a beta and not actual v50 release

**Comment by EithanLlanos** [comment]
My bad:|, ty for helping me
