### ISSUE TITLE
can not load correctly

### ISSUE THREAD

**Issue by HoldBrokenWhell** [Sylkadi/BrutalCompanyMinus#35]
Whether it's installed with other mods  or alone ,Brutal company minus can't load correctly since v50 compatible. I am not sure what‘s causing this issue.
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/15048211/LogOutput.log)

**Comment by Sylkadi** [comment]
LehalCompany -> Properties -> Betas -> Beta participation -> None
![Screenshot_239](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/c307328c-3b9a-4da4-b81b-6a563ccedb33)
![Screenshot_238](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/c3c74b97-e419-4cf2-bf55-19e47c6dc875)

Make sure you are running actual v50 not a beta. Versions 0.11.0 or above will only work with v50 so if you are still using v49 downgrade to before 0.11.0

**Comment by HoldBrokenWhell** [comment]
oh,i forget to change the version from beta,my bad .thank you very much
