### ISSUE TITLE
Stuck on "Waiting for Crew"

### ISSUE THREAD

**Issue by ARandomDeath** [Sylkadi/BrutalCompanyMinus#36]
Hey, so i've added Brutal Company Minus to a modpack my friends and i have been playing on and i was playtesting to see if everything worked. There was no issue landing on a Moon when no custom interior was loaded. As soon as a custom interior was going to be loaded the ship would not Land.

Here is the Error code from BepinEX:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
BrutalCompanyMinus.UI.Update () (at <dd5e6c2ed4b1494f92c98dd5344ae6cd>:IL_008C)

Modlist Code: 018f0036-a560-dc49-9e48-2c764d594f02

Thanks for taking a look :)

**Comment by Sylkadi** [comment]
![Screenshot_269](https://github.com/Sylkadi/BrutalCompanyMinus/assets/101504347/dc51eb86-1048-4f07-a5e7-dc7c84bc0f88)

Leaving this field empty will cause this mod to crash, Set it to 0 instead which will make the mod work.

**Comment by ARandomDeath** [comment]
Thank you so much for the quick response. That fixed it :D
