### ISSUE TITLE
Some events like Pickles can't work well.

### ISSUE THREAD

**Issue by meBVH** [Sylkadi/BrutalCompanyMinus#37]
When we encountered some events like Pickles,it still had other scraps in the falicity, not only the PickleJar.
Maybe some mods conflict with it.

**Comment by meBVH** [comment]
[Uploading LogOutput.log…]()

**Comment by meBVH** [comment]
[LogOutput.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/15140881/LogOutput.log)

**Comment by Sylkadi** [comment]
This is intended, by default at difficulty:0 its 50% and then at difficulty:50 its 90% for most transmutation events. This can be changed in the config.

**Comment by meBVH** [comment]
How do I go about modifying the config if I want to set up all scraps that transform into the transmutation event settings?
I checked the config but i didn't find how to change. Could you tell me in which file I can find this ?

**Comment by Sylkadi** [comment]
VanillaEvents.cfg or ModdedEvents.cfg and there should be a specific Percentage setting for any of the transmutation events.

**Comment by meBVH** [comment]
Well, thanks for the answer. I found it and i suggest that you can change the description clearly.It was very confusing when I first saw it.
