### ISSUE TITLE
Compatibility issues wich break game

### ISSUE THREAD

**Issue by GosTBappo** [Sylkadi/BrutalCompanyMinus#5]
everything with the mod was fine with the compatibility with other mods today I updated to 0.7.4 and the game got unplayable not even being able to press any key ingame or look around. look at screenshot. 

![Lethal Company Screenshot 2024 01 31 - 09 51 29 74](https://github.com/Sylkadi/BrutalCompanyMinus/assets/132256296/eada5d47-1354-4d22-9bdf-44a385d76cee)

I disabled all and turned TooManySuits and MoreShipUpgrades on cause they're mentioned in the error but to my surprise the game worked. After enabling all mods again it just goes back to what is happening in the screenshots.

List of Mods I use:
Evaisa-HookGenPatcher-0.0.5
BepInEx-BepInExPack-5.4.2100
Verity-TooManySuits-1.0.5
AlexCodesGames-AdditionalContentFramework-1.0.3
femboytv-LethalPosters-1.2.0
FlipMods-ReservedItemSlotCore-1.8.17
Ozone-Runtime_Netcode_Patcher-0.2.5
Rune580-LethalCompany_InputUtils-0.6.1
no00ob-LCSoundTool-1.5.0
Clementinise-CustomSounds-2.3.2
HGG-JigglePhysicsPlugin-1.1.2
EliteMasterEric-CleanerLogs-1.0.0
linkoid-DissonanceLagFix-1.0.0
Bobbie-FixRPCLag-1.0.1
Solar32-PerformanceEnhancer-1.3.6
BlueAmulet-LogNeuter-1.0.3
jockie-LethalExpansionCore-1.3.15
Evaisa-LethalLib-0.14.2
NotAtomicBomb-TerminalApi-1.5.1
Zaggy1024-PathfindingLagFix-1.2.1
Zaggy1024-NutcrackerFixes-1.2.2
HolographicWings-LethalExpansion-1.3.25
Sligili-HDLethalCompany-1.5.6
akechii-DiscountAlert-2.3.0
EliteMasterEric-Coroner-1.5.3
notnotnotswipez-MoreCompany-1.7.6
rhydiaan-NicerTeleporters-1.1.1
FutureSavior-Hold_Scan_Button-1.1.1
RugbugRedfern-Skinwalkers-4.0.1
ZTK-ZTKCosmetics-2.0.0
nerdcat-SillyCosmetics-1.8.0
x753-More_Suits-1.4.1
Hexa-Hexas_Cosmetics-0.0.2
Mhz-MoreHead-1.2.5
AlexCodesGames-AdditionalSuits-2.0.0
BatTeam-LethalFashion-1.0.6
MagicalFlyingPurpleTreeSquid-Drive_Suit-1.0.3
Sligili-More_Emotes-1.3.3
ZordAndCo-FunPosters-1.0.5
an0nymooose-An0n_Patches-1.0.3
Jamil-Corporate_Restructure-1.0.6
Justice69-ImmersiveScraps-1.1.7
loaforc-FacilityMeltdown-2.1.1
FlipMods-ReservedFlashlightSlot-1.6.3
FlipMods-ReservedWalkieSlot-1.6.2
FlipMods-HotbarPlus-1.5.7
Drakorle-MoreItems-1.0.2
Stoneman-LethalProgression-1.3.2
bigmcnugget-VanillaContentExpansion-0.1.8
AllToasters-SpectateEnemies-2.2.1
Passiert-Lidl_Moon-1.0.2
Ceelery-Kast-1.0.3
TheFluff-FairAI-1.3.2
anormaltwig-LateCompany-1.0.10
Hexi-HexiBetterShotgun-0.3.2
Coomfy-CoomfyDungeon-1.0.12
malco-Lategame_Upgrades-3.1.1
DrinkableWater-Brutal_Company_Minus-0.7.4
 

Standalone errors:

[Error  : Unity Log] InvalidProgramException: Invalid IL code in (wrapper dynamic-method) RoundManager:DMD<RoundManager::SpawnScrapInLevel> (RoundManager): IL_0005: ldarg.0

Stack trace:
System.RuntimeMethodHandle.GetFunctionPointer () (at <787acc3c9a4c471ba7d971300105af24>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetFunctionPointer (System.Reflection.MethodBase method, System.RuntimeMethodHandle handle) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.DetourHelper.GetNativeStart (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour._TopApply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour._RefreshChain (System.Reflection.MethodBase method) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
MonoMod.RuntimeDetour.Detour..ctor (System.Reflection.MethodBase from, System.Reflection.MethodBase to, MonoMod.RuntimeDetour.DetourConfig& config) (at <4e2760c7517c4ea79c633d67e84b319f>:0)
(wrapper dynamic-method) MonoMod.RuntimeDetour.ILHook+Context.DMD<MonoMod.RuntimeDetour.ILHook+Context::Refresh>(MonoMod.RuntimeDetour.ILHook/Context)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Trampoline<MonoMod.RuntimeDetour.ILHook+Context::Refresh>?633806190(object)
HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.OnILChainRefresh (System.Object self) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
MonoMod.RuntimeDetour.ILHook.Apply () (at <4e2760c7517c4ea79c633d67e84b319f>:0)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.Public.Patching.ManagedMethodPatcher.DetourTo (System.Reflection.MethodBase replacement) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchFunctions.UpdateWrapper (System.Reflection.MethodBase original, HarmonyLib.PatchInfo patchInfo) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
Rethrow as HarmonyException: IL Compile Error (unknown location)
HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
BrutalCompanyMinus.Plugin.Awake () (at <38834ea91526423393153c66cc944a8d>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

When running with mods it gives me this after going into the ship:

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
MoreShipUpgrades.UpgradeComponents.Items.Wheelbarrow.WheelbarrowScript.CheckIfPlayerCarryingWheelbarrowLookSensitivity (System.Single defaultValue) (at <5df352d853744165802bbbbdf4656be7>:IL_003A)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::PlayerLookInput>(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::LateUpdate>(GameNetcodeStuff.PlayerControllerB)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TooManySuits.PluginLoader.Update () (at <434b74dca9584b6891fed93d3e2a47a3>:IL_000E)

I would be very thankful for help but I understand when you say that it's to messy to know what is the problem.

**Comment by GosTBappo** [comment]
just want to confirm that 0.7.3 actually does work with all the other mods and that error appears in newer version.


but in 0.7.3 I have an error in the console

error:
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CorporateRestructure.Component.CreditMonitor.UpdateMonitor () (at <145f04274b9a4d6b9e59d1553ca40844>:IL_0000)
CorporateRestructure.Patch.MonitorPatch.OnPlayerConenct () (at <145f04274b9a4d6b9e59d1553ca40844>:IL_0000)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::ConnectClientToPlayerObject>(GameNetcodeStuff.PlayerControllerB)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::Update>(GameNetcodeStuff.PlayerControllerB)

and:

[Error  : Unity Log] ArgumentException: Patch method System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> BrutalCompanyMinus.Minus.Handlers._LevelParameterRestoring::OnUpdateIL(System.Collections.Generic.IEnumerable<HarmonyLib.CodeInstruction> instructions, System.Reflection.Emit.ILGenerator il) must be static
Stack trace:
HarmonyLib.AttributePatch.Create (System.Reflection.MethodInfo patch, System.Boolean collectIncomplete) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0087)
HarmonyLib.PatchTools+<>c__DisplayClass4_0.<GetPatchMethods>b__0 (System.Reflection.MethodInfo m) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
System.Linq.Enumerable+SelectManySingleSelectorIterator`2[TSource,TResult].MoveNext () (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0051)
System.Linq.Enumerable+WhereEnumerableIterator`1[TSource].ToList () (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0030)
System.Linq.Enumerable.ToList[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_001F)
HarmonyLib.PatchTools.GetPatchMethods (System.Type type, System.Boolean collectIncomplete) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0048)
HarmonyLib.PatchClassProcessor..ctor (HarmonyLib.Harmony instance, System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_00E8)
HarmonyLib.Harmony.CreateClassProcessor (System.Type type, System.Boolean allowUnannotatedType) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
HarmonyLib.Harmony.PatchAll (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:IL_0000)
BrutalCompanyMinus.Plugin.Awake () (at <70615fbc81bc4f28936b022bb44ff170>:IL_0071)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

doesn't seem to be breaking the game

**Comment by Takeapocket** [comment]
same problem

**Comment by Sylkadi** [comment]
Should be fixed in latest
