### ISSUE TITLE
Possible Conflict with Scoopy's Variety Mod

### ISSUE THREAD

**Issue by magicaggy** [Sylkadi/BrutalCompanyMinus#6]
Hi, i'm running into an issue when using this mod and scoopy's. It happened on the planet march, with the dungeon/castle interior. The game generated two different interiors which were desynced between players, and some players would enter the interior, spawn in one of the two interiors and not be able to leave because the exits were in the other interior. I think it has something to do with BCMinus changing map size.

Would it be possible for you to add a config option to prevent BCM from changing the size of the map?

Thank you! If you need me to try and recreate the issue, or need more info, please let me know!

**Comment by Sylkadi** [comment]
Can't replicate, but i did revert the way i changed size to old.
De-sync can happen if not all clients have the mod installed.
