### ISSUE TITLE
[Compatibility] Brutal Company Minus overriding lobby scrap rarity values of Advanced Company

### ISSUE THREAD

**Issue by UmbraMortem13** [Sylkadi/BrutalCompanyMinus#7]
Description:
When starting a lobby and setting any custom rarities, every value works (enemies, scrap amount, scrap value), except for scrap rarity weights. Enemy weights and scrap values are properly modified by Brutal Company Minus during an event, but are otherwise untouched. Uploading bug report to both githubs just in case the fix is simple enough from one side.

Reproduction:
1. Download Advanced Company by PotatoePet
2. Download Brutal Company Minus by DrinkableWater
3. Launch game
4. Pick a moon and set custom scrap rarities
5. Land on moon and enter facility

Expected:
When custom scrap rarities are selected with Advanced Company, it should normally prioritize those values unless there is an item event

Screenshots:
![TEST1](https://github.com/Sylkadi/BrutalCompanyMinus/assets/76416406/58635239-2e33-484b-9b80-d1803233ba56)
![TEST2](https://github.com/Sylkadi/BrutalCompanyMinus/assets/76416406/11df21f4-f773-4df0-b4d9-a3b01a1fd4da)
![SETTINGS](https://github.com/Sylkadi/BrutalCompanyMinus/assets/76416406/98d08506-6a7f-4300-86ba-3f88ab1697ba)

Context:
This is likely an issue that should be fixed on Brutal Company Minus's side, but including on both in case the fix is easier than expected.

Logfiles:
[BrutalCompanyMinusAdvancedCompany.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14148991/BrutalCompanyMinusAdvancedCompany.log)
[AdvancedCompany.log](https://github.com/Sylkadi/BrutalCompanyMinus/files/14149000/AdvancedCompany.log)

Installed Mods:
BepInEx-BepInExPack-5.4.2100
Rune580-LethalCompany_InputUtils-0.6.2
PotatoePet-AdvancedCompany-1.0.148
DrinkableWater-Brutal_Company_Minus-0.7.5 (disabled on 2nd test)

**Comment by TheRealMrKam** [comment]
Hello, noticed it does the same thing with Lethal Quantities. I even desactivated any weather multiplier but it still doesn't allow LQ to do his thing scrap wise, enemy spawn for exemple work fine.

**Comment by TheRealMrKam** [comment]
Just tried the new version updated today that introduce scrap generation, but even with scrap generation false, it still overrides Lethal Quantities scrap generation

Generate and use scrap weights? = false

**Comment by Sylkadi** [comment]
I'm gonna completely change how I handle scrap spawns so it won't conflict with other mods cause there's plenty other mods that change the same scrap list.

**Comment by TheRealMrKam** [comment]
Thank you !

**Comment by Sylkadi** [comment]
This should no longer happen. I tested with advanced company, not with lethal quantities. But should work anyways.
