### ISSUE TITLE
Loading Custom Moons

### ISSUE THREAD

**Issue by daylighted** [Sylkadi/BrutalCompanyMinus#8]
Whenever loading a custom moon in this case "Secret Labs" and "Atlas Abyss" i get this error and im stuck on "Waiting for crew"

[Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
BrutalCompanyMinus.Minus.Handlers.LevelParameterRestoring.StoreUnmodifiedParamaters (SelectableLevel currentLevel) (at <1d4bc940e3a1405799deff7c2cffaf81>:IL_0044)
BrutalCompanyMinus.Plugin.ModifyLevel (SelectableLevel& newLevel) (at <1d4bc940e3a1405799deff7c2cffaf81>:IL_003E)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::LoadNewLevel>(RoundManager,int,SelectableLevel)
StartOfRound+<OpenShipDoors>d__245.MoveNext () (at <af9b1eec498a45aebd42601d6ab85015>:IL_007F)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

**Comment by yyewolf** [comment]
Same here

**Comment by Sylkadi** [comment]
Should be fixed in 0.7.6
